CREATE TABLE BOOKS(
    BOOK_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BOOK_TITLE varchar(60),
    BOOK_AUTHOR varchar(20), 
    BOOK_TYPE varchar(20),
    BOOK_DESCRIPTION varchar(1000),
    BOOK_QUANTITY int, 
    BOOK_COVER mediumblob
);

CREATE TABLE MEMBER(
    MEMBER_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MEMBER_UNAME varchar(30),
    MEMBER_PASS varchar(50),
    MEMBER_CNUMBER int
);

CREATE TABLE LIBRARIAN(
    LIBRARIAN_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LIB_UNAME varchar(30),
    LIB_PASS varchar(50)
);

CREATE TABLE BORROWED_BOOKS(
    BORROW_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID INT REFERENCES BOOKS(BOOK_ID),
    MEMBER_ID INT REFERENCES MEMBER(MEMBER_ID),
    QUANTITY int,
    DUE_DATE DATE
);

INSERT INTO MEMBER (MEMBER_UNAME, MEMBER_PASS, MEMBER_CNUMBER) VALUES ('Member1NealG', 'PassNeal', 0123456789);
INSERT INTO MEMBER (MEMBER_UNAME, MEMBER_PASS, MEMBER_CNUMBER) VALUES ('Member2KristinR', 'PassKristin', 0123456789);
INSERT INTO LIBRARIAN (LIB_UNAME, LIB_PASS) VALUES ('Lib1NathanielS', 'PassNathaniel');
INSERT INTO LIBRARIAN (LIB_UNAME, LIB_PASS) VALUES ('Lib2NigelS', 'PassNigel');

